### ISSUE TITLE
Willing to work with this company

### ISSUE THREAD

**Issue by ayan-biswas0412** [Consult-Strategy/Consult-Strategy1.github.io#3]
Hey there! I'm Ayan Biswas, a Web Developer and Electronics enthusiast.

You can see my works at www.ayanbiswas.me and you can find me in github at https://github.com/ayan-biswas0412

Currently I am Pursuing my Bachelors in Electronics and Telecommunication Engineering at Jadavpur University,Kolkata ,IN

I will be graduating in the year 2023 (expected).

I enjoy builting websites and learning the ecosystem around them.I've been designing website for several years now and learning new skills along the way helping me to become a better developer. I can use the power of Cloud Computing (particularly GCP) to deploy and scale software and IT infrastructure at scale. Have worked with React, JavaScript, CSS, HTML5, PHP, MySQL, UI/UX design and many other tools to create aesthetically pleasing, responsive and functional websites. I pay close attention to details, and have a great understanding of what it takes to build user centric user experiences.

I set clear goals to learn new technologies in the ever-changing IoT field and thrive to build upon my existing knowledge with experience.

**Comment by Consult-Strategy** [comment]
we had read your mail our team will contact you shortly. it will be a telephonic interview so ready for it.

**Comment by Consult-Strategy** [comment]
for(int i=0;i<n;i=i+2){
             for(int j=0;j<n;j++){
                 h[i]=arr[j];
             }
             
         }

**Comment by ayan-biswas0412** [comment]
Thank you for your kind reply @Consult-Strategy
